# path to root directory
# this requires PROJECT_ROOT environment variable to exist
# you can replace it with "." if you want the root to be the current working directory

defaults:
  - default

root_dir: "/home/valentin/projects/test"

data_dir: "/home/valentin/data/features/new_dataset_featv4_surv-nonan.csv"
