_target_: survival_analysis.models.dgm_model.SurvivalDGM

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 5e-4

# scheduler:
#   _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
#   _partial_: true
#   mode: min
#   factor: 0.1
#   patience: 10

in_dim: null
hid_dim: 10
tau: 0.05
